[package]
name = "tOS"
version = "0.1.0"
authors = ["Samuel JD Hood <sjdh@sjdh.us>"]
edition = "2018"

[dependencies]
panic-abort = "0.3.1"
spin = "0.4.9"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]

[package.metadata.cargo-xbuild]
sysroot_path = "../xbuild_sysroot"
